# Site settings Update for my Blog :
title: Anderson Frailey
email: andersonfrailey@gmail.com
description: "Anderson Frailey"
url: "http://andersonfrailey.github.io"
twitter_username: andersonfrailey
github_username:  andersonfrailey

theme: minima
